"""Fixed LangSmith transport for the existing Msty models, not an agent router.

Uses the documented provider-native OpenAI path and the custom-model selector
generated by LangSmith's UI. No secret values, arbitrary hosts, retries, model
fallbacks or new permissions. Disabled is an explicit operator rollback only.
"""
import os

WORKSPACE = 'e8398203-80ef-44ea-8a91-e291faf58173'
HOST = 'https://gateway.smith.langchain.com'
DEEPSEEK_CONFIG_ID = 'ae7376e7-fea6-43cb-b50c-97db118c8c47'
DEEPSEEK_SELECTOR = 'custom/Msty%20DeepSeek%20Flash'
VERSION = 'msty-langsmith-routing-v1'


class GatewayConfigurationError(ValueError):
    """Content-free configuration failure; never fall back around controls."""


def enabled():
    value = os.getenv('MSTY_LLM_GATEWAY_ENABLED', '0')
    if value not in ('0', '1'):
        raise GatewayConfigurationError('Некорректный режим LLM Gateway.')
    return value == '1'


def overrides(profile):
    if not enabled():
        return {}
    if profile not in ('luna', 'deepseek'):
        raise GatewayConfigurationError('Профиль не допущен к активному LLM Gateway.')
    key = os.getenv('LANGSMITH_GATEWAY_API_KEY')
    if not key or not key.strip():
        raise GatewayConfigurationError('Ключ LLM Gateway не настроен; прямой обход запрещён.')
    result = {'api_key': key, 'default_headers': {
        'x-tenant-id': WORKSPACE, 'X-Gateway-App': 'sanare-msty',
        'X-Gateway-Role': profile, 'X-Gateway-Routing-Version': VERSION,
    }}
    if profile == 'luna':
        result.update(base_url=HOST + '/openai/v1', model='gpt-5.6-luna')
    else:
        if os.getenv('MSTY_LLM_GATEWAY_DEEPSEEK_CONFIG_ID') != DEEPSEEK_CONFIG_ID:
            raise GatewayConfigurationError('Проверенная конфигурация DeepSeek Gateway не настроена.')
        result.update(base_url=HOST + '/v1', model=DEEPSEEK_SELECTOR)
    return result
